"""Central configuration: paths, seeds, machine spec, material table, feature lists.

Two parameter sets exist on purpose:

* ``MACHINE_TRUE`` / ``MATERIALS``  - used ONLY by the synthetic generator (the "world").
* ``MACHINE_DATASHEET``             - what an engineer could read off a catalogue; used by the
                                      zero-fit handbook model (experiment E00c) and as starting
                                      point for fitted physics models. It is deliberately a bit
                                      different from the truth, as real datasheets are.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_RAW = ROOT / "data" / "raw"
DATA_PROCESSED = ROOT / "data" / "processed"
DATA_SYNTH = ROOT / "data" / "synthetic"
EXPERIMENTS = ROOT / "experiments"
EXP_RESULTS = EXPERIMENTS / "results"
RESULTS = ROOT / "results"
FIGURES = RESULTS / "figures"
TABLES = RESULTS / "tables"
MODELS = RESULTS / "models"
CACHE = ROOT / ".cache" / "models"   # all fitted models (large, not shipped); regenerated by run_all.sh

SEED = 42
WINDOW_S = 10.0  # one record = mean electrical power over a 10 s steady-state window

# --------------------------------------------------------------------------------------
# Machine (3-axis vertical machining centre, 18.5 kW spindle) - TRUE values (generator only)
# --------------------------------------------------------------------------------------
MACHINE_TRUE = dict(
    p_rated_kw=18.5,          # spindle continuous rating (S1)
    t_rated_nm=118.0,         # rated torque below base speed
    n_base_rpm=1500.0,
    n_max_rpm=8000.0,
    rapid_mm_min=24000.0,
    p_base_kw=2.30,           # controller, hydraulics, cabinet cooling, lighting
    p_amb_kw_per_c=0.020,     # cabinet cooling vs ambient (per deg C above 20)
    p_servo_kw=0.30,          # feed-axis servos enabled
    b_axis_kw_per_mm_min=3.75e-5,   # viscous/friction power of feed axes
    p_coolant_kw={0: 0.0, 1: 1.5, 2: 4.2},  # off / flood / high-pressure through-spindle
    p_conveyor_kw=0.35,       # chip conveyor while cutting
    idle_l0=0.18, idle_l1=2.2e-4, idle_l2=1.1e-8,  # spindle no-load loss: l0 + l1*n + l2*n^2 [kW]
    warm_amp=0.30, warm_tau_min=40.0,              # cold-start friction surplus
    r_cu=0.0668,              # copper-loss coefficient [W/Nm^2]
    eta_inv=0.965,            # inverter efficiency
    p_spindle_off_kw=0.08,
    feed_force_ratio=0.45,    # feed force / cutting force
)

# Catalogue-style numbers (NOT the truth): used by the handbook model
MACHINE_DATASHEET = dict(
    MACHINE_TRUE,
    p_base_kw=2.0,
    p_amb_kw_per_c=0.0,
    p_servo_kw=0.25,
    b_axis_kw_per_mm_min=3.0e-5,
    p_coolant_kw={0: 0.0, 1: 1.2, 2: 3.5},
    p_conveyor_kw=0.3,
    idle_l0=0.15, idle_l1=1.8e-4, idle_l2=0.9e-8,
    warm_amp=0.0,
    r_cu=0.05,
    eta_inv=0.97,
)

# Workpiece materials: Kienzle k_c = kc11 * h^-mc ; Taylor tool life T = T_ref*(vc_ref/vc)^(1/n_T)
MATERIALS = {
    "Al6061":  dict(kc11=700.0,  mc=0.25, vc_min=200.0, vc_max=600.0, vc_ref=400.0, fz_scale=1.0,  ap_scale=1.0, p=0.30),
    "C45":     dict(kc11=1800.0, mc=0.25, vc_min=120.0, vc_max=260.0, vc_ref=180.0, fz_scale=1.0,  ap_scale=1.0, p=0.30),
    "SS316L":  dict(kc11=2300.0, mc=0.21, vc_min=70.0,  vc_max=160.0, vc_ref=110.0, fz_scale=0.85, ap_scale=0.85, p=0.22),
    "Ti6Al4V": dict(kc11=1500.0, mc=0.23, vc_min=40.0,  vc_max=90.0,  vc_ref=60.0,  fz_scale=0.75, ap_scale=0.70, p=0.18),
}
MATERIAL_LIST = list(MATERIALS)
# Catalogue-style Kienzle constants an engineer would look up: close to, but NOT equal to, the generator's
# nominal values (the generator's workpiece lots scatter around MATERIALS). Used by the handbook model and
# as the optimiser start point of the fitted physics model.
MATERIALS_HANDBOOK = {
    "Al6061":  dict(kc11=800.0,  mc=0.28),
    "C45":     dict(kc11=1650.0, mc=0.23),
    "SS316L":  dict(kc11=2400.0, mc=0.23),
    "Ti6Al4V": dict(kc11=1350.0, mc=0.20),
}
TAYLOR_T_REF_MIN = 60.0   # tool life at vc_ref and reference feed
TAYLOR_N = 0.25           # T ~ vc^(-1/n)
TAYLOR_FZ_EXP = 0.5       # T ~ (fz_ref/fz)^exp
TAYLOR_FZ_REF_RATIO = 0.008  # reference fz = 0.008*D

TOOL_DIAMETERS = [6, 8, 10, 12, 16, 20, 25]
TOOL_D_P = [0.08, 0.14, 0.20, 0.22, 0.16, 0.12, 0.08]

# --------------------------------------------------------------------------------------
# Feature sets
# --------------------------------------------------------------------------------------
# Planning features: what the operator/CAM/controller COMMANDS or knows before the cut.
COMMANDED_NUM = [
    "spindle_speed_rpm", "axis_speed_mm_min", "feed_per_tooth_mm", "axial_depth_mm",
    "radial_width_mm", "tool_diameter_mm", "n_flutes", "coolant_mode",
    "tool_age_min", "machine_on_min", "ambient_temp_c",
]
COMMANDED_CAT = ["material"]
# Monitoring signals (measured by the drive): legitimate for condition monitoring,
# NOT for planning / optimisation. Kept out of the main feature set.
SIGNAL_COLS = ["spindle_load_pct", "feed_axes_load_pct"]
# Electrical measurements of the target itself (power = sqrt(3) V I cos(phi)): LEAKAGE.
LEAKY_COLS = ["voltage_v", "current_a", "power_factor"]
TARGET = "power_kw"
